#!/bin/sh
rm -f /etc/default/telegraf

# Systemd
if which systemctl > /dev/null 2>&1 ; then
    systemctl disable telegraf
    rm -f /lib/systemd/system/telegraf.service
# Sysv
else
    if which update-rc.d > /dev/null 2>&1 ; then
        update-rc.d -f telegraf remove
    else
        chkconfig --del telegraf
    fi
    rm -f /etc/init.d/telegraf
fi

